# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 56563fa27a09ccec6d38e4b6a0e45eb8f91bfb5bd86a44ac8ca9ebbb044c94bee3406366a78accf36c520df778d9ce5028d4a18048bb0234f6cf753020bfdce4

test:
  secret_key_base: 3f296fd5fd1320b12c106841a05547a8a3c001ddd8a37f656d99c4501fdd82cd57c2142d345c9f9f08c6666dd5c2fc5fabc8b7df73ccad4135616a1b948bedba

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
